import {ICompany} from '../models/company';

const DESCRIPTION = 'Тут должно быть описание компании. Тут должно быть описание компании. Тут должно быть описание компании. Тут должно быть описание компании. ';
const SCHEDULE = [
    [
        'пн-пт: 09:00-21:00',
        'сб: 10:00-20:00',
        'вс: 10:00-18:00',
    ],
    [
        'пн-пт: 09:00-21:00',
    ],
    [
        'пн-вс: 09:00-18:00',
    ]
];

export const COMPANY_LIST = [
    {
        id: 1,
        title: 'Парикмахерская Елена',
        description: DESCRIPTION,
        isFavorite: true,
        address: 'Россия, г. Москва, ул. Большая Серпуховская, дом. 29, офис 17',
        phone: '+7 (913) 815-71-14',
        rating: 5,
    },
    {
        id: 2,
        title: 'Pronto',
        description: DESCRIPTION,
        isFavorite: true,
        address: 'Москва, ул. Лавочкина, дом № 34',
        phone: '+7 (933) 854-31-65',
        schedule: SCHEDULE[2],
        rating: 5,
    },
    {
        id: 3,
        title: 'НОГТИ & БРОВИ',
        description: DESCRIPTION,
        isFavorite: true,
        address: 'Томск, ул. Мира, д. 20',
        phone: '+7 (952) 655-71-00',
        schedule: SCHEDULE[0],
        rating: 4,
    },
    {
        id: 4,
        title: '"Зефир" студия шугаринга',
        description: DESCRIPTION,
        isFavorite: true,
        address: 'ул. Учебная, 40а',
        phone: '+7 (913) 000-23-23',
        schedule: SCHEDULE[1],
        rating: 5,
    },
    {
        id: 5,
        title: 'Ecosugaring',
        description: DESCRIPTION,
        isFavorite: true,
        address: 'ул. Большая Серпуховская, д. 29',
        phone: '+7 (952) 000-00-00',
        schedule: SCHEDULE[1],
        rating: 3,
    },
    {
        id: 6,
        title: 'Анастасия',
        description: DESCRIPTION,
        isFavorite: false,
        address: 'ул. Большая Серпуховская, д. 29',
        phone: '+7 (913) 815-71-14',
        schedule: SCHEDULE[2],
        rating: 5,
    },
    {
        id: 7,
        title: 'Студия красоты Прованс',
        description: DESCRIPTION,
        isFavorite: false,
        address: 'ул. Большая Серпуховская, д. 29',
        phone: '+7 (913) 815-71-14',
        schedule: SCHEDULE[2],
        rating: 4,
    },
    {
        id: 8,
        title: 'Вероника',
        description: DESCRIPTION,
        isFavorite: false,
        address: 'ул. Большая Серпуховская, д. 29',
        phone: '+7 (913) 815-71-14',
        schedule: SCHEDULE[0],
        rating: 5,
    },
    {
        id: 9,
        title: 'Оксана Хабибулина',
        description: DESCRIPTION,
        isFavorite: false,
        address: 'ул. Большая Серпуховская, д. 29',
        phone: '+7 (913) 815-71-14',
        schedule: SCHEDULE[0],
        rating: 5,
    },
    {
        id: 10,
        title: 'Sweet Nail Studio',
        description: DESCRIPTION,
        isFavorite: false,
        address: 'ул. Большая Серпуховская, д. 29',
        phone: '+7 (913) 815-71-14',
        schedule: SCHEDULE[1],
        rating: 5,
    },
] as ICompany[];
